"""Fixer agent: findings -> Terraform patch -> Semgrep gate -> GitHub PR (dry-run unless open_pr)."""
import json
import re
import subprocess
import sys
from pathlib import Path

import anthropic

from . import compliance, config, frameworks

SEMGREP = str(Path(sys.executable).parent / "semgrep")
PROMPT = """You fix Terraform so it satisfies failing compliance checks found by Prowler in a live AWS account.
Return ONLY a JSON object: {"file": "<path>", "content": "<full new file content>", "summary": "<2-3 sentences>",
"fixes": [{"check_id": "...", "change": "..."}]}.
Rules: change only what the checks require, keep names stable, no secrets in code (use variables or
manage_master_user_password), prefer separate resources (e.g. aws_s3_bucket_public_access_block). Skip checks you
cannot fix in this file and say why in the summary."""


def semgrep(path: Path) -> list[dict]:
    r = subprocess.run([SEMGREP, "--config", "p/terraform", "--metrics=off", "--quiet", "--json", str(path)],
                       capture_output=True, text=True)
    return [{"rule": x["check_id"].split(".")[-1], "line": x["start"]["line"]} for x in json.loads(r.stdout or "{}").get("results", [])]


def propose(repo: Path, account: str, framework: str, file: str = "main.tf", max_checks: int = 8) -> dict:
    top = compliance.top_failing_checks(account, framework, 40)
    tf = (repo / file).read_text()
    # only checks that plausibly map to resources defined in this file
    relevant = [t for t in top if t["check_id"].split("_")[0] in {"s3", "ec2", "rds", "iam", "vpc", "ebs", "kms", "cloudtrail"}][:max_checks]
    info = [{"check_id": t["check_id"], "severity": t["severity"], "failing_resources": t["failing_resources"],
             "remediation": frameworks.check_metadata(t["check_id"]).get("Remediation", {}).get("Recommendation", {})} for t in relevant]
    msg = f"Failing checks:\n{json.dumps(info, indent=1)}\n\nFile {file}:\n```hcl\n{tf}\n```"
    resp = anthropic.Anthropic().messages.create(model=config.MODEL, max_tokens=8000, system=PROMPT,
                                                 messages=[{"role": "user", "content": msg}])
    text = "".join(b.text for b in resp.content if b.type == "text")
    out = json.loads(re.search(r"\{.*\}", text, re.S).group(0))
    return out


def apply(repo: Path, out: dict, branch: str, open_pr: bool = False) -> dict:
    target = repo / out["file"]
    before = semgrep(target)
    sh = lambda *a: subprocess.run(a, cwd=repo, check=True, capture_output=True, text=True).stdout
    sh("git", "checkout", "-B", branch)
    target.write_text(out["content"])
    after = semgrep(target)
    new = [f for f in after if f["rule"] not in {b["rule"] for b in before}]
    result = {"branch": branch, "semgrep_before": len(before), "semgrep_after": len(after), "semgrep_new": new,
              "diff": sh("git", "diff", "--stat"), "pr": None}
    if new:
        result["blocked"] = "Semgrep found new issues introduced by the patch; not opening a PR"
        sh("git", "checkout", "--", out["file"])
        return result
    body = (f"{out['summary']}\n\n**Fixes**\n" + "\n".join(f"- `{f['check_id']}`: {f['change']}" for f in out["fixes"])
            + f"\n\nSemgrep (p/terraform): {len(before)} -> {len(after)} findings, none introduced by this patch.\n"
              "Generated by Prowler Warden from live Prowler OSS findings. Review before merging.")
    sh("git", "-c", "user.name=prowler-warden", "-c", "user.email=warden@users.noreply.github.com", "commit", "-am",
       "fix: remediate Prowler findings (Warden)")
    if open_pr:
        sh("git", "push", "-u", "origin", branch, "--force")
        result["pr"] = sh("gh", "pr", "create", "--title", "Warden: remediate Prowler compliance findings", "--body", body,
                          "--head", branch).strip()
    else:
        result["pr_body"] = body
    return result
