"""Fix-in-code: after (or instead of) a runtime fix, patch the Terraform that owns the resource and open a PR,
so the repository and the cloud never drift. Uses warden-map.json (AWS id -> Terraform address) from the inventory."""
import json
import re
import subprocess
from pathlib import Path

import boto3

from . import fixer

ENV_DIR = "environments/demo"


def _id_from_uid(uid: str) -> str:
    if ":::" in uid:  # s3 arn
        return uid.split(":::")[-1].split("/")[0]
    return uid.split("/")[-1]


def locate(repo: Path, uid: str, region: str, profile: str | None) -> tuple[str, str] | None:
    """-> (file, terraform address) or None when the resource is not managed by this repo."""
    m = json.loads((repo / ENV_DIR / "warden-map.json").read_text())
    rid = _id_from_uid(uid)
    if rid in m:
        return m[rid]["file"], m[rid]["address"]
    if rid.startswith("sg-"):  # recreated resources get new ids: fall back to the (stable) security group name
        try:
            name = boto3.Session(profile_name=profile, region_name=region).client("ec2").describe_security_groups(GroupIds=[rid])["SecurityGroups"][0]["GroupName"]
        except Exception:
            return None
        if f"sg:{name}" in m:
            return m[f"sg:{name}"]["file"], m[f"sg:{name}"]["address"]
    return None


def _block(text: str, header: str, start: int = 0):
    """(start, end) of the brace-balanced block that begins at `header`."""
    i = text.find(header, start)
    if i < 0:
        return None
    j = text.index("{", i)
    depth = 0
    for k in range(j, len(text)):
        depth += text[k] == "{"
        depth -= text[k] == "}"
        if depth == 0:
            return i, k + 1
    return None


def patch_sg_open_ingress(text: str, address: str, check: str) -> tuple[str, int]:
    """Remove ingress blocks open to the internet that match the failing check. Returns (new_text, removed_count)."""
    rtype, name = address.split(".")
    rb = _block(text, f'resource "{rtype}" "{name}"')
    if not rb:
        return text, 0
    body = text[rb[0]:rb[1]]
    port = 22 if check.endswith("port_22") else 3389 if check.endswith("port_3389") else None
    removed, pos = 0, 0
    while True:
        ib = _block(body, "  ingress {", pos)
        if not ib:
            break
        blk = body[ib[0]:ib[1]]
        lo = int(re.search(r"from_port\s*=\s*(\d+)", blk).group(1))
        hi = int(re.search(r"to_port\s*=\s*(\d+)", blk).group(1))
        proto = re.search(r'protocol\s*=\s*"([^"]+)"', blk).group(1)
        opened = "0.0.0.0/0" in blk or "::/0" in blk
        hits_port = port is None or proto == "-1" or lo <= port <= hi
        if opened and hits_port:
            end = ib[1] + 1 if body[ib[1]:ib[1] + 1] == "\n" else ib[1]
            body = body[:ib[0]] + body[end:]
            removed += 1
            pos = ib[0]
        else:
            pos = ib[1]
    return text[:rb[0]] + re.sub(r"\n{3,}", "\n\n", body) + text[rb[1]:], removed


def _git(repo: Path, *a):
    return subprocess.run(["git", *a], cwd=repo, check=True, capture_output=True, text=True).stdout


def fix_in_code(repo: Path, uid: str, check: str, region: str, profile: str | None, note: str, open_pr: bool = False) -> dict:
    loc = locate(repo, uid, region, profile)
    if not loc:
        return {"status": "not-in-code", "note": f"{uid} is not managed by this repository"}
    file, address = loc
    path = repo / ENV_DIR / file
    text = path.read_text()
    if not check.startswith("ec2_securitygroup_allow_ingress"):
        return {"status": "no-patcher", "address": address, "note": f"no deterministic patcher for {check} yet; use the Fixer agent"}
    new, removed = patch_sg_open_ingress(text, address, check)
    if not removed:
        return {"status": "already-compliant-in-code", "address": address, "note": "the Terraform no longer opens this port"}
    branch = f"warden/fix-{address.split('.')[1][:30]}-{check.split('_')[-1]}"
    _git(repo, "checkout", "-q", "master")
    _git(repo, "checkout", "-q", "-B", branch)
    path.write_text(new)
    findings = fixer.semgrep(path)
    body = (f"**{check}** failed on `{uid}`.\n\n{note}\n\nThis PR removes the matching open-to-internet ingress rule from "
            f"`{address}` (`{ENV_DIR}/{file}`) so the code matches what Warden applied in AWS and the next `terraform apply` "
            f"does not re-open it.\n\nSemgrep (p/terraform) findings on the patched file: {len(findings)}.\n\nGenerated by Prowler Warden.")
    _git(repo, "-c", "user.name=prowler-warden", "-c", "user.email=warden@users.noreply.github.com", "commit", "-qam", f"fix: close internet ingress on {address} (Warden)")
    out = {"status": "branch-ready", "address": address, "branch": branch, "removed_rules": removed, "semgrep": len(findings), "pr": None}
    if open_pr:
        _git(repo, "push", "-q", "-u", "origin", branch, "--force")
        out["pr"] = _git(repo, "-c", "core.quotepath=off", "log", "-1", "--format=%H").strip()
        out["pr"] = subprocess.run(["gh", "pr", "create", "--title", f"Warden: close internet ingress on {address}", "--body", body, "--head", branch],
                                   cwd=repo, check=True, capture_output=True, text=True).stdout.strip()
        out["status"] = "pr-opened"
    _git(repo, "checkout", "-q", "master")
    return out
